# Generated by Django 5.1.1 on 2024-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Language',
            field=models.ManyToManyField(help_text='Select a language for this book', to='app.language'),
        ),
    ]
